import { useState, useMemo } from "react";
import type { RequestBodyType } from "../../types/request";
import type { AuthConfig } from "../../types/auth";
import type { HeaderItem } from "../../types/tab";

interface HeadersEditorProps {
  headers: HeaderItem[];
  onChange: (headers: HeaderItem[]) => void;
  bodyType?: RequestBodyType;
  auth?: AuthConfig;
}

// Icons
const EyeIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
    <circle cx="12" cy="12" r="3" />
  </svg>
);

const EyeSlashIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M9.88 9.88a3 3 0 1 0 4.24 4.24" />
    <path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68" />
    <path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61" />
    <line x1="2" y1="2" x2="22" y2="22" />
  </svg>
);

const InfoIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10" />
    <line x1="12" y1="16" x2="12" y2="12" />
    <line x1="12" y1="8" x2="12.01" y2="8" />
  </svg>
);

const CheckIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

interface AutoHeader {
  key: string;
  value: string;
  description: string;
}

export const HeadersEditor: React.FC<HeadersEditorProps> = ({ headers = [], onChange, bodyType, auth }) => {
  const [showAutoGenerated, setShowAutoGenerated] = useState(true);

  // Generate auto-generated headers dynamically
  const autoHeaders = useMemo(() => {
    const generated: AutoHeader[] = [];
    
    if (auth && auth.type !== "None") {
      let authValue = "••••••••••••••••••••••••••••••••••••••••";
      let authKey = "Authorization";

      if (auth.type === "Bearer" && auth.token) {
        authValue = `Bearer ${auth.token}`;
      } else if (auth.type === "Basic") {
        try {
          const credentials = btoa(`${auth.username || ""}:${auth.password || ""}`);
          authValue = `Basic ${credentials}`;
        } catch {
          authValue = "Basic ••••••••";
        }
      } else if (auth.type === "ApiKey") {
         if (auth.add_to === "Header") {
            authKey = auth.key || "x-api-key";
            authValue = "••••••••";
         } else {
            // API key is added to QueryParam, so it doesn't generate a header
            authKey = "";
         }
      }
      
      if (authKey) {
        generated.push({ key: authKey, value: authValue, description: "Automatically generated based on Authorization tab" });
      }
    }
    
    // Default body content type
    let contentType = "";
    if (bodyType === "json") contentType = "application/json";
    else if (bodyType === "xml") contentType = "application/xml";
    else if (bodyType === "text") contentType = "text/plain";
    else if (bodyType === "html") contentType = "text/html";
    else if (bodyType === "x-www-form-urlencoded") contentType = "application/x-www-form-urlencoded";
    else if (bodyType === "form-data") contentType = "multipart/form-data";
    
    if (contentType) {
      generated.push({ key: "Content-Type", value: contentType, description: "Automatically generated based on Body tab" });
    }

    generated.push({ key: "Content-Length", value: "<calculated when request is sent>", description: "Calculated automatically when sending" });
    generated.push({ key: "Host", value: "<calculated when request is sent>", description: "Calculated automatically when sending" });
    generated.push({ key: "User-Agent", value: "MiniPostman/2.0", description: "Default User-Agent" });
    generated.push({ key: "Accept", value: "*/*", description: "Default Accept header" });
    generated.push({ key: "Accept-Encoding", value: "gzip, deflate, br", description: "Default Accept-Encoding" });
    generated.push({ key: "Connection", value: "keep-alive", description: "Default Connection type" });
    
    return generated;
  }, [bodyType, auth]);

  // Filter out auto headers if a custom header overrides it
  const visibleAutoHeaders = useMemo(() => {
    return autoHeaders.filter(autoH => {
      // Find if there is a custom header that overrides this auto header
      const override = (headers || []).find(h => (h.key || "").trim().toLowerCase() === autoH.key.toLowerCase());
      // If there is an override and it is not explicitly disabled, hide the auto header
      return !(override && override.enabled !== false);
    });
  }, [autoHeaders, headers]);

  // Check if we show auto headers or not
  const displayAutoHeaders = showAutoGenerated ? visibleAutoHeaders : [];

  const updateHeader = (index: number, field: keyof HeaderItem, val: string | boolean) => {
    const updated = [...headers];
    updated[index] = { ...updated[index], [field]: val };
    onChange(updated);
  };

  const removeHeader = (index: number) => {
    onChange(headers.filter((_, i) => i !== index));
  };

  const addHeader = () => {
    onChange([...headers, { key: "", value: "", enabled: true }]);
  };

  return (
    <div className="flex flex-col gap-2.5 shrink-0 font-sans text-xs pb-4">
      <div className="flex items-center gap-4 select-none">
        <span className="font-bold text-zinc-300 text-xs tracking-wide">Headers</span>
        <button
          onClick={() => setShowAutoGenerated(!showAutoGenerated)}
          className="flex items-center gap-1.5 px-2 py-1 rounded bg-[#2a2a2a] hover:bg-[#333333] border border-[#3a3a3a] text-zinc-400 hover:text-zinc-200 transition-colors text-[11px]"
        >
          {showAutoGenerated ? <EyeSlashIcon /> : <EyeIcon />}
          {showAutoGenerated ? "Hide auto-generated headers" : "Show auto-generated headers"}
        </button>
      </div>

      <div className="border border-[#383838] rounded-lg bg-[#202020] overflow-hidden shadow-sm">
        <table className="w-full text-left border-collapse text-xs table-fixed">
          <thead>
            <tr className="bg-[#222222] border-b border-[#2e2e2e] text-zinc-400 font-semibold select-none text-xs">
              <th className="w-[30%] border-r border-[#2e2e2e]" style={{ padding: '8px 16px' }}>Key</th>
              <th className="w-[45%] border-r border-[#2e2e2e]" style={{ padding: '8px 16px' }}>Value</th>
              <th className="w-[25%] flex items-center justify-between" style={{ padding: '8px 16px' }}>
                <span>Description</span>
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#282828]">
            {/* Auto Generated Headers */}
            {displayAutoHeaders.map((autoH, idx) => (
              <tr key={`auto-${idx}`} className="bg-[#222222] text-zinc-500 transition-colors group select-none">
                <td className="border-r border-[#2e2e2e]" style={{ padding: '6px 12px' }}>
                  <div className="flex items-center gap-3">
                    {/* Fake disabled checkbox */}
                    <div className="w-4 h-4 rounded-sm border border-[#444] bg-[#2a2a2a] flex items-center justify-center shrink-0 opacity-50 cursor-not-allowed">
                      <CheckIcon />
                    </div>
                    <span className="font-mono text-xs">{autoH.key}</span>
                  </div>
                </td>
                <td className="border-r border-[#2e2e2e]" style={{ padding: '6px 16px' }}>
                  <span className="font-mono text-xs truncate block">{autoH.value}</span>
                </td>
                <td style={{ padding: '6px 16px' }}>
                  <div className="flex items-center gap-2 justify-between">
                    <span className="text-[11px] italic truncate text-zinc-600">{autoH.description}</span>
                    <div title="Auto-generated header" className="shrink-0 text-zinc-500">
                      <InfoIcon />
                    </div>
                  </div>
                </td>
              </tr>
            ))}

            {/* Custom Headers */}
            {(headers || []).map((header, idx) => {
              if (!header) return null;
              const isEnabled = header.enabled !== false;
              return (
                <tr key={`custom-${idx}`} className={`hover:bg-[#202020] transition-colors group ${!isEnabled ? 'opacity-60' : ''}`}>
                  <td className="border-r border-[#2e2e2e]" style={{ padding: '4px 12px' }}>
                    <div className="flex items-center gap-3">
                      <button 
                        onClick={() => updateHeader(idx, "enabled", !isEnabled)}
                        className={`w-4 h-4 rounded-sm border flex items-center justify-center shrink-0 transition-colors ${isEnabled ? 'bg-sky-600 border-sky-500 text-white' : 'border-[#444] bg-[#222] text-transparent hover:border-[#666]'}`}
                        title={isEnabled ? "Disable header" : "Enable header"}
                      >
                        <CheckIcon />
                      </button>
                      <input
                        type="text"
                        value={header.key || ""}
                        onChange={(e) => updateHeader(idx, "key", e.target.value)}
                        placeholder="Key"
                        className={`w-full bg-transparent px-1 py-1 font-mono text-xs focus:outline-none focus:bg-[#2a2a2a] rounded ${!isEnabled ? 'text-zinc-500 line-through decoration-zinc-600' : 'text-zinc-200'}`}
                      />
                    </div>
                  </td>
                  <td className="border-r border-[#2e2e2e]" style={{ padding: '4px 16px' }}>
                    <input
                      type="text"
                      value={header.value || ""}
                      onChange={(e) => updateHeader(idx, "value", e.target.value)}
                      placeholder="Value"
                      className={`w-full bg-transparent px-1 py-1 font-mono text-xs focus:outline-none focus:bg-[#2a2a2a] rounded ${!isEnabled ? 'text-zinc-500 line-through decoration-zinc-600' : 'text-zinc-200'}`}
                    />
                  </td>
                  <td style={{ padding: '4px 16px' }}>
                    <div className="flex items-center justify-between">
                      <input 
                        type="text" 
                        placeholder="Description" 
                        className="w-full bg-transparent px-1 py-1 text-[11px] text-zinc-500 italic focus:outline-none focus:bg-[#2a2a2a] rounded mr-2" 
                      />
                      <button
                        onClick={() => removeHeader(idx)}
                        className="text-zinc-600 hover:text-red-400 p-1 text-sm font-bold opacity-0 group-hover:opacity-100 transition-opacity"
                        title="Remove Header"
                      >
                        ×
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}

            {/* Empty 'Add Header' Row */}
            <tr className="hover:bg-[#202020] transition-colors group cursor-text" onClick={addHeader}>
               <td className="border-r border-[#2e2e2e]" style={{ padding: '4px 12px' }}>
                 <div className="flex items-center gap-3">
                    <div className="w-4 h-4 shrink-0" /> {/* Spacer for checkbox */}
                    <input
                      type="text"
                      placeholder="Key"
                      className="w-full bg-transparent px-1 py-1 font-mono text-xs focus:outline-none text-zinc-500 pointer-events-none"
                    />
                 </div>
               </td>
               <td className="border-r border-[#2e2e2e]" style={{ padding: '4px 16px' }}>
                 <input
                    type="text"
                    placeholder="Value"
                    className="w-full bg-transparent px-1 py-1 font-mono text-xs focus:outline-none text-zinc-500 pointer-events-none"
                  />
               </td>
               <td style={{ padding: '4px 16px' }}>
                 <span className="text-zinc-500 text-[11px] italic px-1 block py-1">Description</span>
               </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};
